### ISSUE TITLE
Failed to open pixel shader (Lancos3.cso)

### ISSUE THREAD

**Issue by EmilBorgSwe** [Alexkral/AviSynthAiUpscale#4]
Hello!
For some reason, the update can't load one of the pixel shaders. I'm certain I've updated the .avsi for this and the .dll for AviSynthShader. Please help, I'm at a loss.

**Comment by Alexkral** [comment]
There is no reference to "Lancos3.cso" in AiUpscale.avsi, but to "Lanczos3.cso", you can check that.

If it's correct, you probably need to change line 96 in AiUpscale.avsi to reflect the full path to the Shaders folder. This problem is described here:

[https://forum.doom9.org/showthread.php?p=1919073#post1919073](url)
